'use client'

import Image from 'next/image'
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion' // kept for parallax only
import { ButtonLink, Container } from '@/components/ui'
import { HeroStats } from './HeroStats'

// TODO: Replace with CMS-managed content
const heroContent = {
    headlineTop: 'Strategic Opportunities',
    headlineBottom: 'Growth & Income Returns',
    subheadline: `Generated by property selected for upside potential. Protected with systematic capital diversification.`,
    stats: [
        { value: '9.12%', label: 'Return from Previous Year*', highlight: true },
        { value: '$173M+', label: 'Funds Under Management' },
        { value: '$10,000', label: 'Low Minimum Investment' },
    ],
    ctaPrimary: { label: 'Join the Fund', href: '/apply' },
}

export function HeroSection() {
    const shouldReduceMotion = useReducedMotion()
    const { scrollY } = useScroll()
    const backgroundY = useTransform(
        scrollY,
        [0, 800],
        shouldReduceMotion ? [0, 0] : [0, 90]
    )

    return (
        <section className="relative sm:min-h-[90vh] md:min-h-[80vh] lg:min-h-[70vh] flex flex-col overflow-hidden bg-sogif-navy">
            {/* Background Image */}
            <motion.div className="absolute inset-0" style={{ y: backgroundY }}>
                <Image
                    src="https://www.datocms-assets.com/192130/1768821769-background.webp?w=1920&fit=max&auto=format"
                    alt=""
                    fill
                    className="object-cover object-[center_10%] opacity-40"
                    priority
                />
                <div className="absolute inset-0 bg-gradient-to-r from-sogif-navy/70 via-sogif-navy/30 to-sogif-navy/15" />
                <div className="absolute inset-0 bg-gradient-to-t from-sogif-navy/60 via-sogif-navy/30 to-sogif-navy/15" />
            </motion.div>

            {/* Content - flex-1 to fill available space, centered vertically */}
            <Container className="relative z-10 flex-1 flex items-center w-full pb-12 pt-32 md:pb-12 lg:pb-20">
                <div className="w-full grid lg:grid-cols-12 gap-8 lg:gap-16 items-center">
                    {/* Left Column - Text Content (7/12) */}
                    <div className="lg:col-span-8 xl:col-span-7 text-center lg:text-left w-full max-w-2xl lg:max-w-none mx-auto lg:mx-0">
                        <h1 className="type-display text-white mb-5 md:mb-6">
                            <span className="relative inline-block">
                                {heroContent.headlineTop}
                                <span className="absolute -bottom-1 left-0 w-full h-1 bg-gradient-to-r from-sogif-gold/80 to-sogif-gold/20 rounded-full" />
                            </span>
                            <br />
                            <span className="text-sogif-cyan-light">{heroContent.headlineBottom}</span>
                        </h1>

                        <p className="type-body text-white/90 mb-6 md:mb-8 max-w-xl mx-auto lg:mx-0">
                            {heroContent.subheadline}
                        </p>

                        <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center lg:justify-start">
                            <ButtonLink
                                href={heroContent.ctaPrimary.href}
                                variant="primary"
                                size="lg"
                                glow="gold"
                                className="group focus-ring-inverse"
                            >
                                {heroContent.ctaPrimary.label}
                            </ButtonLink>
                        </div>
                    </div>

                    {/* Right Column - Stats Display (5/12) */}
                    <div className="lg:col-span-4 lg:col-start-9">
                        <HeroStats stats={heroContent.stats} />
                    </div>
                </div>
            </Container>

            {/* Past performance disclaimer */}
            <p className="relative type-caption text-white/70 text-center pb-4 px-4">
                *Past performance is not a reliable indicator of future performance.
            </p>
        </section>
    )
}
