'use client'

import Image from 'next/image'
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion' // kept for parallax only
import { ButtonLink, Container } from '@/components/ui'
import { HeroStats } from './HeroStats'

// TODO: Replace with CMS-managed content
const heroContent = {
    headlineTop: 'Strategic Opportunities',
    headlineBottom: 'Growth & Income Returns',
    subheadline: `Generated by a property portfolio with upside potential. Protected with systematic capital diversification.
    `,
    stats: [
        { value: '10%', label: 'Return from Previous Year*', highlight: true },
        { value: '$170M+', label: 'Funds Under Management' },
        { value: '$10,000', label: 'Low Min. Investment' },
    ],
    ctaPrimary: { label: 'Join the Fund', href: '/apply' },
    ctaSecondary: { label: 'Performance', href: '#performance' },
}

export function HeroSection() {
    const shouldReduceMotion = useReducedMotion()
    const { scrollY } = useScroll()
    const backgroundY = useTransform(
        scrollY,
        [0, 600],
        shouldReduceMotion ? [0, 0] : [0, 90]
    )

    return (
        <section className="relative sm:min-h-[90vh] md:min-h-[80vh] xxl:min-h-[75vh] flex flex-col overflow-hidden bg-sogif-navy">
            {/* Background Image */}
            <motion.div className="absolute inset-0" style={{ y: backgroundY }}>
                <Image
                    src="https://www.datocms-assets.com/192130/1768821769-background.webp?w=1920&fit=max&auto=format"
                    alt=""
                    fill
                    className="object-cover object-[center_10%] opacity-40"
                    priority
                />
                <div className="absolute inset-0 bg-gradient-to-r from-sogif-navy/70 via-sogif-navy/30 to-sogif-navy/15" />
                <div className="absolute inset-0 bg-gradient-to-t from-sogif-navy/60 via-sogif-navy/30 to-sogif-navy/15" />
            </motion.div>

            {/* Content - flex-1 to fill available space, centered vertically */}
            <Container className="relative z-10 flex-1 flex items-center w-full pb-12 pt-32 md:pb-12 lg:pb-20">
                <div className="w-full flex flex-col lg:grid lg:grid-cols-2 gap-8 lg:gap-16 items-center">
                    {/* Left Column - Text Content */}
                    <div className="text-center lg:text-left w-full max-w-2xl lg:max-w-none mx-auto lg:mx-0">
                        <h1 className="type-display text-white mb-5 md:mb-6">
                            <span className="relative inline-block">
                                {heroContent.headlineTop}
                                <span className="absolute -bottom-1 left-0 w-full h-1 bg-gradient-to-r from-sogif-gold/80 to-sogif-gold/20 rounded-full" />
                            </span>
                            <br />
                            <span className="text-sogif-cyan-light">{heroContent.headlineBottom}</span>
                        </h1>

                        <p className="type-body text-white/90 mb-6 md:mb-8 max-w-xl mx-auto lg:mx-0">
                            {heroContent.subheadline}
                        </p>

                        <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center lg:justify-start mb-8 lg:mb-0">
                            <ButtonLink
                                href={heroContent.ctaPrimary.href}
                                variant="primary"
                                size="lg"
                                glow="gold"
                                className="group focus-ring-inverse"
                            >
                                {heroContent.ctaPrimary.label}
                            </ButtonLink>
                            <ButtonLink
                                href={heroContent.ctaSecondary.href}
                                variant="outline"
                                size="lg"
                            >
                                {heroContent.ctaSecondary.label}
                                <svg className="w-5 h-5 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                                </svg>
                            </ButtonLink>
                        </div>
                    </div>

                    {/* Right Column - Stats Display */}
                    <HeroStats stats={heroContent.stats} />
                </div>
            </Container>
        </section>
    )
}
